<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Devices\Illumination\Nuova cartella1\**" />
    <EmbeddedResource Remove="Devices\Illumination\Nuova cartella1\**" />
    <None Remove="Devices\Illumination\Nuova cartella1\**" />
  </ItemGroup>

</Project>
