<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Devices\DoorDevice\Commands\**" />
    <EmbeddedResource Remove="Devices\DoorDevice\Commands\**" />
    <None Remove="Devices\DoorDevice\Commands\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlaisePascal.SmartHouse.Domain\BlaisePascal.SmartHouse.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Devices\Dto\" />
  </ItemGroup>

</Project>
